DROP TABLE IF EXISTS `AG_LAW_PARTNER`;

CREATE TABLE `AG_LAW_PARTNER` (
	`COMPNUM`	varchar(32)	NULL,
	`ID`	varchar(64)	NOT NULL,
	`EMAIL`	varchar(128)	NULL,
	`PASSWORD`	varchar(256)	NULL,
	`NAME`	varchar(64)	NULL,
	`MOBILE`	varchar(32)	NULL,
	`PHONE`	varchar(32)	NULL,
	`FAX`	varchar(32)	NULL,
	`ADDR1_1`	varchar(32)	NULL,
	`ADDR1_2`	varchar(64)	NULL,
	`ADDR1_3`	varchar(256)	NULL,
	`ADDR2_1`	varchar(32)	NULL,
	`ADDR2_2`	varchar(64)	NULL,
	`ADDR3_1`	varchar(32)	NULL,
	`ADDR3_2`	varchar(64)	NULL,
	`LICENSE`	varchar(256)	NULL
);

DROP TABLE IF EXISTS `AG_USER`;

CREATE TABLE `AG_USER` (
	`ID`	varchar(64)	NOT NULL,
	`PASSWORD`	varchar(256)	NULL,
	`NAME`	varchar(64)	NOT NULL,
	`EMAIL`	varchar(128)	NULL,
	`MOBILE`	varchar(32)	NULL
);

DROP TABLE IF EXISTS `AG_LAW_FEE`;

CREATE TABLE `AG_LAW_FEE` (
	`CLASSIFY_T`	varchar(16)	NOT NULL,
	`CLASSIFY_M`	varchar(1)	NULL,
	`TERM`	integer	NULL,
	`FEE`	integer	NULL,
	`DISCOUNT_R`	smallint	NULL
);

DROP TABLE IF EXISTS `AG_LAW_PAYMENT`;

CREATE TABLE `AG_LAW_PAYMENT` (
	`COMPNUM`	varchar(32)	NULL,
	`CLASSIFY_T`	varchar(16)	NOT NULL,
	`CLASSIFY_M`	varchar(1)	NULL,
	`TERM`	integer	NULL,
	`PAY_G`	varchar(1)	NULL	COMMENT 'B : 계좌이체,
C : 카드',
	`AMOUNT`	integer	NULL
);

DROP TABLE IF EXISTS `AG_LAW_OBJ`;

CREATE TABLE `AG_LAW_OBJ` (
	`OBJ_ID`	varchar(64)	NOT NULL,
	`ID`	varchar(64)	NOT NULL,
	`KIND`	varchar(10)	NULL,
	`AMOUNT`	bigint	NULL,
	`ADDR_1`	varchar(32)	NULL,
	`ADDR_2`	varchar(64)	NULL,
	`ADDR_3`	varchar(256)	NULL,
	`DISCOUNT_C`	varchar(1)	NULL,
	`CONTRACT_D`	date	NULL,
	`BOND_DISC_R`	float	NULL,
	`ETC`	varchar(1024)	NULL,
	`REG_DATE`	datetime	NULL
);

DROP TABLE IF EXISTS `AG_LAW_AUCTION`;

CREATE TABLE `AG_LAW_AUCTION` (
	`COMPNUM`	varchar(32)	NULL,
	`AGENT_ID`	varchar(64)	NOT NULL,
	`OBJ_ID`	varchar(64)	NOT NULL,
	`USER_ID`	varchar(64)	NOT NULL,
	`END_D`	datetime	NULL,
	`AUCTION_AMOUNT`	bigint	NULL,
	`AUCTION_DATE`	datetime	NULL
);

ALTER TABLE `AG_LAW_PARTNER` ADD CONSTRAINT `PK_AG_LAW_PARTNER` PRIMARY KEY (
	`COMPNUM`,
	`ID`
);

ALTER TABLE `AG_USER` ADD CONSTRAINT `PK_AG_USER` PRIMARY KEY (
	`ID`
);

ALTER TABLE `AG_LAW_FEE` ADD CONSTRAINT `PK_AG_LAW_FEE` PRIMARY KEY (
	`CLASSIFY_T`,
	`CLASSIFY_M`,
	`TERM`
);

ALTER TABLE `AG_LAW_PAYMENT` ADD CONSTRAINT `PK_AG_LAW_PAYMENT` PRIMARY KEY (
	`COMPNUM`,
	`CLASSIFY_T`,
	`CLASSIFY_M`,
	`TERM`
);

ALTER TABLE `AG_LAW_OBJ` ADD CONSTRAINT `PK_AG_LAW_OBJ` PRIMARY KEY (
	`OBJ_ID`,
	`ID`
);

ALTER TABLE `AG_LAW_AUCTION` ADD CONSTRAINT `PK_AG_LAW_AUCTION` PRIMARY KEY (
	`COMPNUM`,
	`AGENT_ID`,
	`OBJ_ID`,
	`USER_ID`
);

ALTER TABLE `AG_LAW_PARTNER` ADD CONSTRAINT `FK_AG_USER_TO_AG_LAW_PARTNER_1` FOREIGN KEY (
	`ID`
)
REFERENCES `AG_USER` (
	`ID`
);

ALTER TABLE `AG_LAW_PAYMENT` ADD CONSTRAINT `FK_AG_LAW_PARTNER_TO_AG_LAW_PAYMENT_1` FOREIGN KEY (
	`COMPNUM`
)
REFERENCES `AG_LAW_PARTNER` (
	`COMPNUM`
);

ALTER TABLE `AG_LAW_PAYMENT` ADD CONSTRAINT `FK_AG_LAW_FEE_TO_AG_LAW_PAYMENT_1` FOREIGN KEY (
	`CLASSIFY_T`
)
REFERENCES `AG_LAW_FEE` (
	`CLASSIFY_T`
);

ALTER TABLE `AG_LAW_PAYMENT` ADD CONSTRAINT `FK_AG_LAW_FEE_TO_AG_LAW_PAYMENT_2` FOREIGN KEY (
	`CLASSIFY_M`
)
REFERENCES `AG_LAW_FEE` (
	`CLASSIFY_M`
);

ALTER TABLE `AG_LAW_PAYMENT` ADD CONSTRAINT `FK_AG_LAW_FEE_TO_AG_LAW_PAYMENT_3` FOREIGN KEY (
	`TERM`
)
REFERENCES `AG_LAW_FEE` (
	`TERM`
);

ALTER TABLE `AG_LAW_OBJ` ADD CONSTRAINT `FK_AG_USER_TO_AG_LAW_OBJ_1` FOREIGN KEY (
	`ID`
)
REFERENCES `AG_USER` (
	`ID`
);

ALTER TABLE `AG_LAW_AUCTION` ADD CONSTRAINT `FK_AG_LAW_PARTNER_TO_AG_LAW_AUCTION_1` FOREIGN KEY (
	`COMPNUM`
)
REFERENCES `AG_LAW_PARTNER` (
	`COMPNUM`
);

ALTER TABLE `AG_LAW_AUCTION` ADD CONSTRAINT `FK_AG_LAW_PARTNER_TO_AG_LAW_AUCTION_2` FOREIGN KEY (
	`AGENT_ID`
)
REFERENCES `AG_LAW_PARTNER` (
	`ID`
);

ALTER TABLE `AG_LAW_AUCTION` ADD CONSTRAINT `FK_AG_LAW_OBJ_TO_AG_LAW_AUCTION_1` FOREIGN KEY (
	`OBJ_ID`
)
REFERENCES `AG_LAW_OBJ` (
	`OBJ_ID`
);

ALTER TABLE `AG_LAW_AUCTION` ADD CONSTRAINT `FK_AG_LAW_OBJ_TO_AG_LAW_AUCTION_2` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `AG_LAW_OBJ` (
	`ID`
);

