USE AGENCY_PLATFORM;

CREATE TABLE AG_USER (
	ID	integer	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PASSWORD	varchar(256)	NULL,
	NAME	varchar(64)	NOT NULL,
	EMAIL	varchar(128)	NULL,
	MOBILE	varchar(32)	NULL,
	PICTURE	varchar(512) NULL,
	ROLE	varchar(16)	NULL,
	REG_DATE	datetime	NULL,
	MOD_DATE	datetime	NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 ROW_FORMAT=DYNAMIC
;

CREATE TABLE AG_LAW_PARTNER (
	COMPNUM	varchar(32)	NOT NULL PRIMARY KEY,
	ID		integer	NOT NULL,
	EMAIL		varchar(128) NULL,
	PASSWORD	varchar(256) NULL,
	NAME	varchar(64)	NULL,
	MOBILE	varchar(32)	NULL,
	PHONE	varchar(32)	NULL,
	FAX	varchar(32)	NULL,
	ADDR1_1	varchar(32)	NULL,
	ADDR1_2	varchar(64)	NULL,
	ADDR1_3	varchar(256)	NULL,
	ADDR2_1	varchar(32)	NULL,
	ADDR2_2	varchar(64)	NULL,
	ADDR3_1	varchar(32)	NULL,
	ADDR3_2	varchar(64)	NULL,
	LICENSE	varchar(512)	NULL,
	REG_DATE	datetime	NULL,
	MOD_DATE	datetime	NULL,
    FOREIGN KEY(ID) references AG_USER(ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 ROW_FORMAT=DYNAMIC
;

CREATE TABLE AG_LAW_FEE (
	CLASSIFY_T	varchar(16)	NOT NULL,
	CLASSIFY_M	varchar(1)	NOT NULL,
	TERM	integer	NOT NULL,
	FEE	integer	NULL,
	DISCOUNT_R	smallint	NULL,
	REG_DATE	datetime	NULL,
	MOD_DATE	datetime	NULL,
    PRIMARY KEY(CLASSIFY_T, CLASSIFY_M, TERM)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 ROW_FORMAT=DYNAMIC
;

CREATE TABLE AG_LAW_PAYMENT (
	PAY_ID	integer	NOT NULL auto_increment PRIMARY KEY,
	COMPNUM	varchar(32)	NULL,
	CLASSIFY_T	varchar(16)	NOT NULL,
	CLASSIFY_M	varchar(1)	NULL,
	TERM	integer	NULL,
	PAY_G	smallint	NULL	COMMENT "B : 계좌이체,C : 카드",
	AMOUNT	integer	NULL,
	REG_DATE	datetime	NULL,
    FOREIGN KEY(COMPNUM) references AG_LAW_PARTNER(COMPNUM),
    FOREIGN KEY(CLASSIFY_T,CLASSIFY_M,TERM) references AG_LAW_FEE(CLASSIFY_T,CLASSIFY_M,TERM)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 ROW_FORMAT=DYNAMIC
;

CREATE TABLE AG_LAW_OBJ (
	OBJ_ID	integer	NOT NULL auto_increment PRIMARY KEY,
	ID	integer	NOT NULL,
	KIND	varchar(10)	NULL,
	AMOUNT	bigint	NULL,
	ADDR_1	varchar(32)	NULL,
	ADDR_2	varchar(64)	NULL,
	ADDR_3	varchar(256)	NULL,
	DISCOUNT_C	varchar(1)	NULL,
	CONTRACT_D	date	NULL,
	BOND_DISC_R	float	NULL,
	ETC	varchar(1024)	NULL,
	REG_DATE	datetime	NULL,
	MOD_DATE	datetime	NULL,
    FOREIGN KEY(ID) references AG_USER(ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 ROW_FORMAT=DYNAMIC
;

CREATE TABLE AG_LAW_AUCTION (
	AUCTION_ID	integer	NOT NULL auto_increment PRIMARY KEY,
	COMPNUM	varchar(32)	NULL,
	AGENT_ID	integer	NOT NULL,
	OBJ_ID	integer	NOT NULL,
	USER_ID	integer	NOT NULL,
	END_D	datetime	NULL,
	AUCTION_AMOUNT	bigint	NULL,
	REG_DATE	datetime	NULL,
	MOD_DATE	datetime	NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 ROW_FORMAT=DYNAMIC
;

CREATE TABLE AG_LAW_LOG (
	LOG_ID	integer	NOT NULL auto_increment PRIMARY KEY,
	LOG_DD	varchar(2)	NULL,
	SERVICE_DATE	varchar(8)	NULL,
	SERVICE_TIME	varchar(6)	NULL,
	ID	integer	NULL,
	ROLE	varchar(16)	NULL,
	SERVICE_NO	integer	NULL,
	REG_DATE	datetime	NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 ROW_FORMAT=DYNAMIC
;

CREATE TABLE SPRING_SESSION (
	PRIMARY_ID	char(36)	NOT NULL,
	SESSION_ID	char(36)	NULL,
	CREATION_TIME	bigint	NULL,
	LAST_ACCESS	bigint	NULL,
	MAX_INACTIVE_INTERVAL	int	NULL,
	EXPIRY_TIME	bigint	NULL,
	PRINCIPAL_NAME	varchar(100)	NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 ROW_FORMAT=DYNAMIC
;

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
	ATTRIBUTE_NAME	varchar(200)	NULL,
	SESSION_PRIMARY_ID	char(36)	NOT NULL,
	ATTRIBUTE_BYTES	BLOB	NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 ROW_FORMAT=DYNAMIC
;

--------------------------------------------

--alter table AG_LAW_PARTNER drop foreign key FK_AG_USER_TO_AG_LAW_PARTNER_1;
--alter table AG_LAW_PAYMENT drop foreign key FK_AG_LAW_PARTNER_TO_AG_LAW_PAYMENT_1;
--alter table AG_LAW_PAYMENT drop foreign key FK_AG_LAW_FEE_TO_AG_LAW_PAYMENT;
--alter table AG_LAW_OBJ drop foreign key FK_AG_USER_TO_AG_LAW_OBJ_1;
--alter table AG_LAW_AUCTION drop foreign key FK_AG_LAW_PARTNER_TO_AG_LAW_AUCTION;
--alter table AG_LAW_AUCTION drop foreign key FK_AG_LAW_OBJ_TO_AG_LAW_AUCTION;
--alter table SPRING_SESSION_ATTRIBUTES drop foreign key FK_SPRING_SESSION_TO_SPRING_SESSION_ATTRIBUTES_1;

drop table AG_LAW_PARTNER cascade;
drop table AG_USER cascade;
drop table AG_LAW_FEE cascade;
drop table AG_LAW_PAYMENT cascade;
drop table AG_LAW_OBJ cascade;
drop table AG_LAW_AUCTION cascade;
drop table AG_LAW_LOG cascade;
drop table SPRING_SESSION cascade;
drop table SPRING_SESSION_ATTRIBUTES cascade;